-- MySQL Script generated by MySQL Workbench
-- Fri Apr 12 18:08:12 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Airport`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Airport` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Airport` (
  `Airport_code` INT NOT NULL,
  `City` VARCHAR(45) NULL,
  `State` VARCHAR(45) NULL,
  `Name` VARCHAR(45) NULL,
  PRIMARY KEY (`Airport_code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Airplane_Type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Airplane_Type` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Airplane_Type` (
  `Type_name` VARCHAR(45) NOT NULL,
  `Max_seats` INT NULL,
  `Company` VARCHAR(45) NULL,
  PRIMARY KEY (`Type_name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Airplane`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Airplane` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Airplane` (
  `Airplane_id` INT NOT NULL,
  `Total_no_of_seats` INT NULL,
  `Airplane_type_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Airplane_id`),
  INDEX `Airplane_type_name_idx` (`Airplane_type_name` ASC) VISIBLE,
  CONSTRAINT `fk_Airplane_Type_Airplane`
    FOREIGN KEY (`Airplane_type_name`)
    REFERENCES `mydb`.`Airplane_Type` (`Type_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Flight`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Flight` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Flight` (
  `Number` INT NOT NULL,
  `Airline` VARCHAR(45) NULL,
  `Weekdays` VARCHAR(45) NULL,
  PRIMARY KEY (`Number`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Fare`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Fare` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Fare` (
  `Code` INT NOT NULL,
  `Flight_Number` INT NOT NULL,
  `Amount` INT NULL,
  `Restrictions` VARCHAR(45) NULL,
  PRIMARY KEY (`Code`, `Flight_Number`),
  INDEX `fk_Flight_Fare_idx` (`Flight_Number` ASC) VISIBLE,
  CONSTRAINT `fk_Flight_Fare`
    FOREIGN KEY (`Flight_Number`)
    REFERENCES `mydb`.`Flight` (`Number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`FLIGHT_LEG`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`FLIGHT_LEG` ;

CREATE TABLE IF NOT EXISTS `mydb`.`FLIGHT_LEG` (
  `Leg_no` INT NOT NULL,
  `Flight_number` INT NOT NULL,
  `Departing_Airport_code` INT NOT NULL,
  `Arriving_Airport_code` INT NOT NULL,
  `Scheduled_dep_time` VARCHAR(45) NOT NULL,
  `Scheduled_arr_time` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Leg_no`, `Flight_number`),
  INDEX `fk_Airport_FLIGHT_LEG_idx` (`Departing_Airport_code` ASC) VISIBLE,
  INDEX `fk_Flight_FLIGHT_LEG_idx` (`Flight_number` ASC) VISIBLE,
  INDEX `fk_Airport_FLIGHT_LEG_arr_idx` (`Arriving_Airport_code` ASC) VISIBLE,
  CONSTRAINT `fk_Airport_FLIGHT_LEG_dep`
    FOREIGN KEY (`Departing_Airport_code`)
    REFERENCES `mydb`.`Airport` (`Airport_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Flight_FLIGHT_LEG`
    FOREIGN KEY (`Flight_number`)
    REFERENCES `mydb`.`Flight` (`Number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Airport_FLIGHT_LEG_arr`
    FOREIGN KEY (`Arriving_Airport_code`)
    REFERENCES `mydb`.`Airport` (`Airport_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`LEG_INSTANCE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`LEG_INSTANCE` ;

CREATE TABLE IF NOT EXISTS `mydb`.`LEG_INSTANCE` (
  `Date` DATE NOT NULL,
  `Flight_number` INT NOT NULL,
  `Leg_no` INT NOT NULL,
  `Airplane_id` INT NOT NULL,
  `Departing_Airport_code` INT NULL,
  `Arriving_Airport_code` INT NULL,
  `Dep_time` DATETIME NULL,
  `Arr_time` DATETIME NULL,
  `No_of_avail_seats` INT NULL,
  PRIMARY KEY (`Leg_no`, `Flight_number`, `Date`),
  INDEX `fk_Airplane_LEG_INSTANCE_idx` (`Airplane_id` ASC) VISIBLE,
  INDEX `fk_Airport_LEG_INSTANCE_idx` (`Departing_Airport_code` ASC) VISIBLE,
  INDEX `fk_Airport_LEG_INSTANCE_arr_idx` (`Arriving_Airport_code` ASC) INVISIBLE,
  INDEX `fk_FLIGHT_LEG_LEG_INSTANCE_idx` (`Leg_no` ASC, `Flight_number` ASC) VISIBLE,
  CONSTRAINT `fk_FLIGHT_LEG_LEG_INSTANCE`
    FOREIGN KEY (`Leg_no` , `Flight_number`)
    REFERENCES `mydb`.`FLIGHT_LEG` (`Leg_no` , `Flight_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Airplane_LEG_INSTANCE`
    FOREIGN KEY (`Airplane_id`)
    REFERENCES `mydb`.`Airplane` (`Airplane_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Airport_LEG_INSTANCE_dep`
    FOREIGN KEY (`Departing_Airport_code`)
    REFERENCES `mydb`.`Airport` (`Airport_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Airport_LEG_INSTANCE_arr`
    FOREIGN KEY (`Arriving_Airport_code`)
    REFERENCES `mydb`.`Airport` (`Airport_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Seat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Seat` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Seat` (
  `Seat_no` INT NOT NULL,
  `Flight_number` INT NOT NULL,
  `Leg_no` INT NOT NULL,
  `Date` DATE NOT NULL,
  `Customer_name` VARCHAR(45) NULL,
  `CPhone` VARCHAR(45) NULL,
  PRIMARY KEY (`Leg_no`, `Flight_number`, `Date`, `Seat_no`),
  INDEX `fk_LEG_INSTANCE_Seat_idx` (`Leg_no` ASC, `Flight_number` ASC, `Date` ASC) VISIBLE,
  CONSTRAINT `fk_LEG_INSTANCE_Seat`
    FOREIGN KEY (`Leg_no` , `Flight_number` , `Date`)
    REFERENCES `mydb`.`LEG_INSTANCE` (`Leg_no` , `Flight_number` , `Date`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CAN_LAND`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`CAN_LAND` ;

CREATE TABLE IF NOT EXISTS `mydb`.`CAN_LAND` (
  `Airplane_Type_Name` VARCHAR(45) NOT NULL,
  `Airport_Code` INT NOT NULL,
  PRIMARY KEY (`Airplane_Type_Name`, `Airport_Code`),
  INDEX `fk_Airport_CAN_LAND_idx` (`Airport_Code` ASC) VISIBLE,
  CONSTRAINT `fk_Airport_CAN_LAND`
    FOREIGN KEY (`Airport_Code`)
    REFERENCES `mydb`.`Airport` (`Airport_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Airplane_Type_CAN_LAND`
    FOREIGN KEY (`Airplane_Type_Name`)
    REFERENCES `mydb`.`Airplane_Type` (`Type_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
