-- MySQL Script generated by MySQL Workbench
-- Wed Apr 10 22:24:35 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Stadium`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Stadium` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Stadium` (
  `Stadium_id` INT NOT NULL,
  `Stadium_name` VARCHAR(45) NULL,
  `SeatNumber` INT NULL,
  PRIMARY KEY (`Stadium_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Team`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Team` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Team` (
  `Team_id` INT NOT NULL,
  `Team_name` VARCHAR(45) NULL,
  `Region` INT NULL,
  `Stadium_id` INT NOT NULL,
  PRIMARY KEY (`Team_id`),
  INDEX `fk_Stadium_Team_idx` (`Stadium_id` ASC) VISIBLE,
  CONSTRAINT `fk_Stadium_Team`
    FOREIGN KEY (`Stadium_id`)
    REFERENCES `mydb`.`Stadium` (`Stadium_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Player`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Player` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Player` (
  `Player_id` INT NOT NULL,
  `Player_name` VARCHAR(45) NULL,
  `Position` VARCHAR(45) NULL,
  `BackNumber` INT NULL,
  `team_id` INT NULL,
  PRIMARY KEY (`Player_id`),
  INDEX `fk_Team_Player_idx` (`team_id` ASC) VISIBLE,
  CONSTRAINT `fk_Team_Player`
    FOREIGN KEY (`team_id`)
    REFERENCES `mydb`.`Team` (`Team_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Game`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Game` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Game` (
  `Stadium_id` INT NOT NULL,
  `game_id` DATE NOT NULL,
  `Hometeam_id` INT NOT NULL,
  `Awayteam_id` INT NOT NULL,
  `Hometeam_score` INT NULL,
  `Awayteam_score` INT NULL,
  PRIMARY KEY (`Stadium_id`, `game_id`),
  INDEX `fk_hometeam_game_idx` (`Hometeam_id` ASC) VISIBLE,
  INDEX `fk_awayteam_game_idx` (`Awayteam_id` ASC) VISIBLE,
  CONSTRAINT `fk_Stadium_game`
    FOREIGN KEY (`Stadium_id`)
    REFERENCES `mydb`.`Stadium` (`Stadium_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_hometeam_game`
    FOREIGN KEY (`Hometeam_id`)
    REFERENCES `mydb`.`Team` (`Team_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_awayteam_game`
    FOREIGN KEY (`Awayteam_id`)
    REFERENCES `mydb`.`Team` (`Team_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
